#!/usr/bin/perl

use 5.36.0;
use feature 'defer';
use open           qw( :std :encoding(UTF-8) );
use File::Basename qw(basename dirname);
use List::Util     qw(reduce);
use IPC::Open3;

my @workspaces = ( glob("~/dev/*/*/"), glob("~/workspaces/*/") );
my $pid        = open3(
  my $child_in,
  my $child_out,
  my $child_err,
  'rofi -dmenu -format "i:s"'
);

for my $dir (@workspaces) {
  print $child_in ( basename($dir) . "\n" );
}

my ( $choice_idx, $choice_label ) = split /:/, <$child_out>;
chomp $choice_label;
say "$choice_idx:$choice_label";
waitpid( $pid, 0 );
exit(0) if ( ( $? << 8 ) != 0 );    # no choice was made

my $choice_dir = $choice_idx > 0 ? $workspaces[$choice_idx] : "~";
my $ret        = $? >> 8;

die("error occured with the rofi command") if $ret != 0;
say "selected: $workspaces[$choice_idx]";

# executing rt-new-session with session label and sessions
# default directory
my $scripts_dir = dirname(__FILE__);
`$scripts_dir/rt-new-session "$choice_label" "$choice_dir" &`;
`notify-send "Session \"$choice_label\" activated" &`;
