#!/usr/bin/perl 
use FindBin;
use lib "$FindBin::Bin/../lib";

use 5.20.0;
use warnings;
use autodie;
use Tmux;
use Path;
use Zoxide;
use Rofi;
use ArrayUtils;
use Pango;

my @active_dirs = Tmux::list_dirs();
my @zoxide_dirs = Zoxide::list_dirs();

@active_dirs = sort @active_dirs;
@zoxide_dirs = sort @zoxide_dirs;

my @dirs =
  ArrayUtils::remove_common_among( \@active_dirs, \@zoxide_dirs, );

# removing root from directory (cannot name session with dirname)
splice( @dirs, 0, 1 ) if $dirs[0] eq "/";

my @active_sessions = Tmux::list_sessions();
my @inits           = Tmux::list_session_inits();

say "@active_sessions";

my @active_n_inits =
  ArrayUtils::unique( sort ( @active_sessions, @inits ) );

my @sessions = ( @active_n_inits, @dirs, );

my $ani_size = @active_n_inits;
my ( $idx, $input ) = Rofi::dmenu(
  "Choose a session",
  map { Pango::markup $_ } @sessions,
);

exit 0 if not defined $idx;

if ( $idx > -1 ) {
  Tmux::activate_session( $sessions[$idx] );
}
elsif ( $input ne "" ) {
  Tmux::activate_session($input);
}

